### ISSUE TITLE
Representation of the wave doesn't appear to change or is totally wrong

### ISSUE THREAD

**Issue by BabyYoda88** [timovanoverveld/APPOF#3] opened 2019-12-11 12:18 UTC
Measurements done gave some interesting results. Attached is the measurement file for verification and some images to clarify. 
For every measurement done, the script returns the same waveform image as seen in the last two images. This error returns for different measurments sets.

Another interesting bug caused the first four images. Not only is the waveform representation really off, the projected vs real position images are not making any sense, leading to a high distrust in the created .dat files. 

![Waveform image 1 11](https://user-images.githubusercontent.com/58291227/70620638-15472b80-1c18-11ea-867f-a7a1b63cfe60.png)
![Waveform image 1 13](https://user-images.githubusercontent.com/58291227/70620639-15472b80-1c18-11ea-835b-809528b7dde1.png)
![Location data 1 11](https://user-images.githubusercontent.com/58291227/70620640-15dfc200-1c18-11ea-9a96-7340bd5fc8c9.png)
![Location data 1 13](https://user-images.githubusercontent.com/58291227/70620641-15dfc200-1c18-11ea-8247-5dcf2eb224f5.png)
![Waveform image 1 2](https://user-images.githubusercontent.com/58291227/70620643-16785880-1c18-11ea-8cc6-f8aa90d9a65d.png)
![Waveform image 1 10](https://user-images.githubusercontent.com/58291227/70620645-16785880-1c18-11ea-9725-9700b024168c.png)

**Comment by timovanoverveld** [comment] 2019-12-13 08:58
Could you add the names of the directories and files which gave these specific images?

**Comment by BabyYoda88** [comment] 2019-12-13 09:34
9-12-2019, Wave with particles, 
Meting_1, files 1.1, 1.10, 1.11,1.13 give the images above.
Meting_2, files 2.10, 2.13, 2.17, 2.18, 2.22 2.2, and more in this file give similar results
Quick glance at the analysis of other measurements tells me that this error occurs at every measurement.

**Comment by timovanoverveld** [comment] 2019-12-13 12:57
The issue is resolved in branch validation
The fault consisted of two parts:
- A miscalculation in the number of lines, which is fixed in commit 716fcd4
- Inaccuracies in the removal of particles (ed2a0fd) and subsequent thresholding (a05c543, e71be17)

**Closed** 2019-12-13 13:52 UTC
Labels: bug, invalid
